// Builds the slim dataset the site's pages load, from js/data.js.
//
// js/data.js stays the master copy (the digest routine and every script
// edit and read it), but at 1.3 MB it was loaded by every page before it
// could render. 62% of it is the full write-ups (`body`) and timelines,
// which are shown only in a matter's panel after sign-in. This writes:
//   js/data-lite.js        RELAW_DATA without body/timeline; each case
//                          with either gets hasFull: true
//   matters/data/<id>.json {body, timeline}, fetched by the panel on open
//   js/matter-text.json    {id: write-up text}, fetched the first time
//                          someone searches, so search still finds words
//                          that appear only in a write-up
//
// Run by .github/workflows/prerender.yml after every change to js/data.js;
// locally:  deno run --allow-read --allow-write scripts/build_data_lite.ts

const src = await Deno.readTextFile("js/data.js");
// deno-lint-ignore no-explicit-any
const data: any = new Function(src + "; return RELAW_DATA;")();

const text: Record<string, string> = {};
const keep = new Set<string>();
await Deno.mkdir("matters/data", { recursive: true });
// deno-lint-ignore no-explicit-any
const lite = { ...data, cases: data.cases.map((c: any) => {
  const { body, timeline, ...rest } = c;
  const hasBody = Array.isArray(body) && body.length > 0;
  const hasTimeline = Array.isArray(timeline) && timeline.length > 0;
  if (!hasBody && !hasTimeline) return rest;
  keep.add(`${c.id}.json`);
  Deno.writeTextFileSync(`matters/data/${c.id}.json`, JSON.stringify({ body: hasBody ? body : [], timeline: hasTimeline ? timeline : [] }));
  if (hasBody) text[c.id] = body.join(" ");
  return { ...rest, hasFull: true };
}) };

for await (const e of Deno.readDir("matters/data")) {
  if (e.isFile && e.name.endsWith(".json") && !keep.has(e.name)) await Deno.remove(`matters/data/${e.name}`);
}

const header = "/* Generated by scripts/build_data_lite.ts from js/data.js -- do not edit.\n" +
  "   Full write-ups and timelines live in matters/data/<id>.json. */\n";
const out = header + "const RELAW_DATA = " + JSON.stringify(lite) + ";\n";
await Deno.writeTextFile("js/data-lite.js", out);
await Deno.writeTextFile("js/matter-text.json", JSON.stringify(text));
console.log(`data-lite.js ${out.length} bytes (data.js ${src.length}); ${keep.size} matter detail files; search text ${JSON.stringify(text).length} bytes`);
