#!/usr/bin/env python3
"""Score Case Value Calculator backtest results (see the protocol in
case_valuation_project/backtest/README.md) and write the scored set to
js/backtest-results-data.js for the public calibration page.

  python3 scripts/score_backtest.py
"""

import glob
import json
import re

RESULTS = "case_valuation_project/backtest/results/*.json"
OUT = "js/backtest-results-data.js"
FEE_LABEL = re.compile(r"\bfees?\b", re.I)


def ex_fee_range(issues):
    lo = hi = 0.0
    used = 0
    for i in issues:
        if FEE_LABEL.search(i.get("label") or ""):
            continue
        p, d = i.get("probabilityRange"), i.get("damagesRange")
        if not p or not d:
            continue
        lo += p[0] * d[0]
        hi += p[1] * d[1]
        used += 1
    return ([round(lo), round(hi)] if used else None), used


def score(record):
    p = record.get("prediction") or {}
    o = record["outcome"]
    main_award = o.get("amount")
    fees = o.get("attorneysFeesAtTrial") or 0
    all_in_actual = (main_award or 0) + fees if main_award is not None else None
    top = p.get("damagesRange")
    best = p.get("bestGuessValue")
    exf, used = ex_fee_range(p.get("issues") or [])
    declined = record.get("status") == 200 and not top

    def inside(rng, x):
        return None if not rng or x is None else (rng[0] <= x <= rng[1])

    def err(pred, x):
        return None if pred is None or not x else round((pred - x) / x, 3)

    return {
        "id": record["id"],
        "caseName": (record.get("source") or {}).get("caseName"),
        "court": (record.get("source") or {}).get("court"),
        "decided": (record.get("source") or {}).get("decided"),
        "sourceUrl": (record.get("source") or {}).get("url"),
        "ranAt": record.get("ranAt"),
        "category": p.get("category"),
        "role": p.get("roleLabel"),
        "declined": declined,
        "error": record.get("error"),
        "exFees": {"predictedRange": exf, "issuesUsed": used, "actual": main_award, "hit": inside(exf, main_award)},
        "allIn": {
            "predictedRange": top, "bestGuess": best, "actual": all_in_actual,
            "hit": inside(top, all_in_actual), "bestGuessError": err(best, all_in_actual),
        },
        "outcomeDescription": o.get("description"),
        "appellateChange": o.get("appellateChange"),
    }


def main():
    rows = [score(json.load(open(f))) for f in sorted(glob.glob(RESULTS))]
    scored = [r for r in rows if not r["declined"] and not r["error"]]
    summary = {
        "cases": len(rows),
        "scored": len(scored),
        "declined": sum(1 for r in rows if r["declined"]),
        "errors": sum(1 for r in rows if r["error"]),
        "exFeesHits": sum(1 for r in scored if r["exFees"]["hit"]),
        "exFeesScorable": sum(1 for r in scored if r["exFees"]["hit"] is not None),
        "allInHits": sum(1 for r in scored if r["allIn"]["hit"]),
        "allInScorable": sum(1 for r in scored if r["allIn"]["hit"] is not None),
        "medianBestGuessError": None,
    }
    errs = sorted(r["allIn"]["bestGuessError"] for r in scored if r["allIn"]["bestGuessError"] is not None)
    if errs:
        summary["medianBestGuessError"] = errs[len(errs) // 2]
    payload = {"generatedAt": max((r["ranAt"] or "") for r in rows) if rows else None, "summary": summary, "cases": rows}
    with open(OUT, "w") as f:
        f.write("/* Generated by scripts/score_backtest.py from case_valuation_project/backtest/results/. Do not edit. */\n")
        f.write("window.BACKTEST_RESULTS = " + json.dumps(payload, indent=1) + ";\n")
    print(json.dumps(summary, indent=1))
    for r in rows:
        print(f"  {r['id']}: ex-fees {r['exFees']['predictedRange']} vs {r['exFees']['actual']} -> {r['exFees']['hit']} | all-in {r['allIn']['predictedRange']} best {r['allIn']['bestGuess']} vs {r['allIn']['actual']} -> {r['allIn']['hit']}")


if __name__ == "__main__":
    main()
